SELECT
    -- Identification & Region
    "uwi",
    "license_num",
    "bu",
    "region",
    "sub_region",
    "area",
    "property",
    "production_date",
    "normalized_day_simple",
    "normalized_day_enhanced",
    "pm_site_name",
    "pm_site_type",
    "pm_product_type_group",
    "pm_bu",
    "pm_region",
    "pm_sub_region",
    "pm_area",
    "pm_property",
    -- Time & Yield Ratios (SI)
    "hours_on",
    "hours_calc",
    "working_interest",
    "shrinkage_gas",
    "shrinkage_fuel",
    "shrinkage_oil",
    "yield_m3pm3",
    "gor_m3pm3",
    -- Produced Volumes (Metric/SI)
    "produced_gas_e3m3",
    "produced_gas_shrunk_e3m3",
    "produced_gas_less_fuel_e3m3",
    "produced_gas_m3e",
    "produced_gas_shrunk_m3e",
    "produced_ngl_m3",
    "produced_ngl_from_gas_m3",
    "produced_oil_m3",
    "produced_oil_shrunk_m3",
    "produced_cond_m3",
    "produced_total_m3e",
    "produced_total_shrunk_m3e",
    "produced_water_m3",
    "produced_src_water_m3",
    -- Load Recovery (Metric)
    "load_oil_m3",
    "load_water_m3",
    "load_fluid_m3",
    "load_oil_inv_m3",
    "load_water_inv_m3",
    -- Injection & Disposal (Metric)
    "inj_gas_e3m3",
    "inj_co2_e3m3",
    "inj_poly_m3",
    "inj_water_m3",
    "inj_target_m3",
    "disp_water_m3",
    "src_water_m3",
    "wellhead_gas_e3m3",
    "lift_gas_e3m3",
    "wellhead_effluent_e3m3",
    "wellhead_effluent_m3e",
    -- Pressures & Temperatures (SI - kPa/Celsius)
    "casing_kpa",
    "tubing_kpa",
    "mwhip_kpa",
    "target_tubing_kpa",
    "static_kpa",
    "differential_kpa",
    "pipe_kpa",
--    "lift_gas_casing_kpa",
--    "lift_gas_tubing_kpa",
--    "lift_gas_static_kpa",
--    "lift_gas_differential_kpa",
--    "effluent_casing_kpa",
--    "effluent_tubing_kpa",
--    "effluent_static_kpa",
--    "effluent_differential_kpa",
--    "wellhead_gas_casing_kpa",
--    "wellhead_gas_tubing_kpa",
--    "wellhead_gas_static_kpa",
--    "wellhead_gas_differential_kpa",
    -- Mechanical & Physical Settings
    "joints_to_fluid",
    "joints_in_hole",
    "coeff",
    --"orifice",
    "temperature",
    "lift_gas_temperature",
    "effluent_temperature",
    "wellhead_gas_temperature",
    "torque",
    "rpm",
    "spm",
    "stroke_length",
    -- Descriptions & Database IDs
--    "dtc_description",
--    "sub_dtc_description",
--    "grs_wells_id",
--    "inj_gas_id",
--    "inj_co2_id",
--    "src_water_id",
--    "inj_disposal_id",
--    "inj_polymer_id",
--    "inj_water_id",
--    "wellhead_gas_id",
--    "lift_gas_id",
--    "effluent_id",
--    "battery_code",
--    "comment",
    -- Date Numerics (Simplified)
--    "datetime_week_start",
--    "datetime_week_end",
--    "datenum_days_from_today",
--    "datenum_weeks_from_this_week",
--    "datenum_months_from_this_month",
--    "datenum_yyyy",
--    "datenum_yyyymmdd",
--    "datenum_yyyymm",
--    "datenum_mm",
--    "datenum_yyyyww",
--    "datenum_ww",
--    "datenum_day_of_year",
--    "datenum_day_of_month",
--    "datenum_day_of_week"
        "well_name"
FROM "production"."fdc_full_production_uwi_daily"
WHERE "uwi" = '100152206905W600' -- Replace with your specific UWI
ORDER BY "production_date";